### ISSUE TITLE
User testing findings

### ISSUE THREAD

**Issue by KatiaSitspot** [GSG-G7/sitspot#13]
SITSPOT PROTOTYPE USER TESTING 23/10/19

Key learnings

## Things to change:

- **Landing page:** 
  * [x] remove the magnifying glass
  * [x] remove subscribe to our newsletter
  * [x] remove social media icons
  * [x] separate input for city and country
  * [x] in the welcome blurb, add a link to the “About us” page

- **Profile page**
    * [x] Remove the screen where we ask if they want to send their information (this will be mandatory)

- **Results page**
    * [x] Search section/functionality should be shown all the time
    * [x] “8 search results” should be shown on top of search results

- [ ] In the **individual SitSpot page**: a new wireframe is likely to be designed 
    - Underneath the photo
    - Plus Button for should say “add a recommendation” in the same style as the rest 
    - Remove Google map link
    - Remove social links
    - Add number of recommendations
    - Add “Add a recommendation” 
    - In the recommendation
    - Instead of the current layout, we will see 1 icon paired with a comment about that criteria, followed by …
   - The full review, followed by …
   - User profile
   - Add a “more” button to expand the rest of the text.

- **Add a recommendation flow**
    * [x] All recommendations will be vetted by an admin before they go live
    * [ ] Reviews that are added from an individual sitspot page will be added to the ongoing log of recommendations
    * [ ] Recommendations that are added from the home page or the menu will generate a brand new entry which the admin will have to check (form will be longer and will include the sitspot’s ID info: name, country, city, URL.)

## **Katia to provide 7 Typeforms**:
1.    Contributor profile
2.    STAY questionnaire including sitspot ID info
3.    STAY questionnaire without the sitspot ID info
4.    EAT/DRINK questionnaire including sitspot ID info
5.    EAT/DRINK questionnaire without the sitspot ID info
6.    SHOP questionnaire including sitspot ID info
7.    SHOP questionnaire without the sitspot ID info

**Comment by Amoodaa** [comment]
i edited ur comment so we can check the stuff we finished.

**Comment by KatiaSitspot** [comment]
A sitspot is an individual business (accommodation, restaurant, shop).

ID are the elements that admins will use to identify a business: name of the business, country, city, URL. 

 

*	When a user – say Travelbug Pete lands on the landing page, he clicks on “add a recommendation”
*	He will be asked whether he wants to recommend a place to STAY EAT or SHOP.
*	He will then be sent the form: “accommodation including ID” and fill it in and submit
*	Admin will then find the location address on Google, read the submission, validate and publish

 

*	When a user – say Maria backpacker lands on a sitspot page – say one created by Travelbug Pete, she reads his recommendation then clicks on “add a recommendation”
*	She will then be sent the form: “accommodation without ID” (because those details are already in) and fill it in and submit
*	Admin will read the submission, validate and publish
