### ISSUE TITLE
User stories / pages

### ISSUE THREAD

**Issue by teenie-quaggard** [GSG-G7/sitspot#3]
All assets including pages and acceptance criteria can be found here:
https://1drv.ms/u/s!AjYAThCZglCywnBHts38kriP5SGf?e=l8o6Bo

**Comment by teenie-quaggard** [comment]
@KatiaSitspot - thank you for posting this link!

**Comment by KatiaSitspot** [comment]
You’re welcome

**Comment by aminalakhsham** [comment]
@KatiaSitspot thank you for the document, we wait for the the final version.

**Comment by KatiaSitspot** [comment]
@teenie-quaggard I have emailed you my log in to Typeform as discussed. Looking forward to hear if the team will use Typeform as the tool to fill in the questionnaire and retrieve data for the search, or will come up with a bespoke tool!

**Comment by KatiaSitspot** [comment]
Please a link to a folder including all documents. (same link as shared a few days ago) [https://1drv.ms/u/s!AjYAThCZglCywnBHts38kriP5SGf?e=l8o6Bo](url)
I draw your attention to particular docs:
- an updated doc called PAGES v5 detailing each page 
- a doc illustrating how the process works called "how to add a recommendation and what ...."
- in folder 04, screenshots from Trip Advisor
I am currently revising the questionnaire in light of the decision not to have ratings at all

**Comment by teenie-quaggard** [comment]
Will open up a new issues with updated asset links.
