### ISSUE TITLE
Initial handover

### ISSUE THREAD

**Issue by teenie-quaggard** [GSG-G7/sitspot#77]
@KatiaSitspot - as you know, our initial handover will be next week. 
This will be the time for us to look through the in progress app and create any notes for improvements that need to be done for the team.

Unfortunately, my only availability for the handover would be 11-1pm at our new space at 113-115 Fonthill Road, 2nd Floor. Does this work with your schedule? It might not actually take us 2hours and we may finish early.

Like we spoke about already, it would be a good idea to line up one or two potential users who can test the in-progress app. It may be that we can tackle some of the smaller bits of feedback that we get from them, but bigger changes will be simply noted for a future sprint.

The following week, we will complete our final handover remotely with the team on Thursday November 21st. 

Thanks @KatiaSitspot !

**Comment by KatiaSitspot** [comment]
For the initial handover, do you mean next Wednesday or Thursday? I can do either day from 11-1pm. Might be best if I come to your office as opposed to remotely?

 

Re: lining up the testers, can you please clarify: shall I ask them to be available during our session so we interact with them? Or will I be sending them a link and some tasks/questions?

**Comment by teenie-quaggard** [comment]
Hi @KatiaSitspot !

Our initial handover will be this Wednesday November 13th from 11am-1pm at the *new* Space4. Ideally the testers would be available for a maximum of 30minutes some time during our time together! They can come to the space or we can send them the link and speak to them a video conference. 

Our final handover will be next Thursday November 21st, time TBA, remotely.

Does that all work for you?

**Comment by KatiaSitspot** [comment]
Hi,

Yes, I can come to your office at 11am on the 13th.

Shall we go for 2 testers? Do you advise they should be brand new to the concept? That they know about the concept but haven’t tested it? That I ask some of our previous testers to test again?

Shall I aim to get one at 11.30, and one at 12am so we have time to debrief before and after? 

 

For the 21st, I have a meeting at the British Library from 9.45-10.45am, but could potentially move it if needs be.

 

Katia

**Comment by teenie-quaggard** [comment]
Hi @KatiaSitspot - sorry, I somehow missed this last message of yours.

In regards to testing...I think it may be best if we cancel the external testers for now. There has been an escalation in the Gaza strip and I have not been able to have contact with the team. Because of this, I'm not sure if there is a hosted / live version of the site yet, which would be needed for the external testing. 

Let's just the two of us meet tomorrow and I can run the app locally so that we can go through and make notes of bugs or amendments that we'd like to see fixed over the next week. See you at 11 tomorrow!

**Comment by teenie-quaggard** [comment]
Hi @KatiaSitspot - just as a follow up to my last email, I have tried to run the project locally but I think I am missing some key information from the team. As I am unsure of whether or not anyone will have access to the internet today, I think it may be better to reschedule our meeting for Monday next week. Would that work for you?

If so, let's wait to see if any of the team gets back to me today, and if so we can continue with the initial handover of tomorrow. If not, we can reschedule for Monday. I can confirm with you via telephone tonight.

Apologies for the delay - there are just some things that we cannot control!

**Comment by KatiaSitspot** [comment]
Hi Kristina,

I have seen your note about the escalation in the Gaza trip and I feel so anxious. I really hope that Amin and the team are ok? 

I’d rather we meet tomorrow, but I understand if we need to reschedule to Monday. You can just call me today as soon as you know.

Best wishes
