### ISSUE TITLE
Initial feedback from Kristina

### ISSUE THREAD

**Issue by teenie-quaggard** [GSG-G7/sitspot#86]
Hi everyone, just had a peek at the Heroku and it's looking awesome! Great work over there - I have heard that things are a bit crazy so a big thank you for continuing to work at home.

I will be going through the app with Katia tonight around 5pm London time so I'll be able to send some initial feedback then.

Looking through it, here are a few things that I have already noticed:

1. Add recommendation button is not properly aligned (in mobile or desktop)
![Screen Shot 2019-11-14 at 09 14 46](https://user-images.githubusercontent.com/37771591/68843538-34f23f00-06c0-11ea-9b7f-41a7386b5a32.png)

2. If possible, Katia would prefer that countries/cities that do not yet have a Sitspot are not shown on the dropdown in the search. Preferably, it would look something like this, with the numbers representing the number of sitspots in that place:
https://www.holiable.com/lodging/hotel/
![Screen Shot 2019-11-14 at 09 26 19](https://user-images.githubusercontent.com/37771591/68843946-dbd6db00-06c0-11ea-9539-fbb98b97486f.png)

3. Would be great if the nav menu automatically closes after a link is clicked on, as opposed to staying open
![Screen Shot 2019-11-14 at 09 31 05](https://user-images.githubusercontent.com/37771591/68844312-818a4a00-06c1-11ea-96a3-628b72007360.png)

4. Copy for FAQs still need to be updated (plus there are some typos on the headings that have been added to heroku, so please have a look when you are adding the new stuff in)
https://onedrive.live.com/view.aspx?cid=b2508299104e0036&page=view&resid=B2508299104E0036!8649&parId=B2508299104E0036!8738&authkey=!AOxjVt8ILmwns8s&app=Word

5. The link for adding a new Sitspot reads a bit too casual and has a capitalisation error. I would suggest 'Would you like to add a new SitSpot?
![Screen Shot 2019-11-14 at 09 34 37](https://user-images.githubusercontent.com/37771591/68844689-168d4300-06c2-11ea-8ed6-cfb1a3e98417.png)

6. KeyWords in the filter search should be spelled 'Keywords'
![Screen Shot 2019-11-14 at 09 37 07](https://user-images.githubusercontent.com/37771591/68844858-5e13cf00-06c2-11ea-99f5-0519374635ba.png)

7. Ideally the keywords menu will eventually have icons beside the words
https://user-images.githubusercontent.com/56404750/68476342-54055280-0222-11ea-8d34-257d6857206e.png

8. At the moment, I haven't been able to search any existing sitspots as I don't think they are linked. Katia did mention that  she has made 3 of each business type

9. When trying to add a Sitspot, I get a 500 when trying to add a photo and cannot move one
![Screen Shot 2019-11-14 at 09 41 55](https://user-images.githubusercontent.com/37771591/68845265-12adf080-06c3-11ea-8618-f9113e52ce91.png)

10. I haven't seen the user info form - does that come next?

Overall, SUPER work. I am extremely impressed by everything so far. Ideally it would be best if the add a sitspot functionality was working by tonight, and that there is at least one Sitspot page rendered so that Katia can have an idea of what it looks like. Thanks team!!!!! You are awesome!

**Comment by Amoodaa** [comment]
actually the typeform page comes after the add a recommendation page.
the add a new place form, only the first pic is mandatory and its kinda hard coded, so please try again, and only update the first pic
the typeform page link is `/add-review/:type/:sitspotId` i.e: ``/add-review/stay/22`
and after that it will wait to be read by mods and checked on as active, so then we can fetch it in our queries, since our queries only get the active ones in the search page

**Comment by Amoodaa** [comment]
and ill at least provide a fake page for the place review, so katia can see how it looks like, if i got really stuck on viewing a place with reviews. sorry for the inconvenience.

**Comment by KatiaSitspot** [comment]
Hi team, thanks you SO much, I can tell a lot of hard work has gone into it already!

**Comments / additions to Kristina’s points**

4. Copy for FAQs still need to be updated
	Katia: I have now read it again and made a few amendments. See on this document https://1drv.ms/u/s!AjYAThCZglCyxCLsY1bfCC5sJ7PL?e=Gs3aJm 
	So please remove the current headings: About SitSpot, Sustainability, and Writing recommendation. Instead, we will have 4 headings: 
•	Knowing which businesses to recommend
•	Reasons for recommending a business
•	Sustainability criteria
•	Process of adding a recommendation
Those headings should be expandable, to reveal the questions.

5. The link for adding a new Sitspot reads a bit too casual and has a capitalisation error. I would suggest 'Would you like to add a new SitSpot?
Katia: I think it would be confusing to have a Search button, a Add a recommendation button, and in between “Would you like to add a new sitspot. I can discuss this with Kristina later today.

9. When trying to add a Sitspot, I get a 500 when trying to add a photo and cannot move one
	Katia:
•	I have tried to add a new place, but after I uploaded my picture, I clicked “done” but nothing happened.
•	Therefore I can’ see how this page links towards the Typeform questionnaire
•	At step 1, the picture is completely distorted on mobile
•	I need to discuss step 7 with Kristina. We are asking them to upload pictures on the “Add a recommendation” page, and then again in the Typeform questionnaire. If we are asking them to upload picture only from the “Add a recommendation” page at step 7, they need to be able to upload up to 10 pictures, and ideally multi upload and edit pics (especially rotate). 
•	Once we are all clear on the process, question 9 in FAQ needs to be reviewed.


**Katia’s additional points**
10.	Landing page
•	Can you please align the Shop button with the Stay button. It’s currently too long.
•	Please mirror the font as per layout on https://marvelapp.com/7g2ah3f/screen/62522589 i.e. WHAT ARE YOU LOOKING FOR? And FILTER should be in capital letters. Not sure if “Search” and “Add your recommendation” are in the right font/size?
•	Copy for “Welcome to our beta site”. Please write “Find” with a capital letter.
•	Suggested sitspots: I presume that you are working on this section and this will link to sitspots already in the database? Note that the beach images look super distorted on desktop.
•	Please confirm we are going to have a different image on each load as previously discussed.

11.	Research results page
•	Font should be consistent across all pages, e.g. “WHAT ARE YOU LOOKING FOR” should be in capital letters. Currently there’s a mix of font colour (it should be all grey as per marvelapp layouts) and font sizes.
 

•	It’s hard to comment on the search function as I don’t think it’s fully implemented yet?
What do you recommend if user selects a country e.g. Slovenia (from the shortlist in the dropdown menu)  but they also select “Shop” whereas the only sitspot we have in the database is a place to Stay? Ideally we should have a message saying something like “No result for your search, but you might be interested in those alternatives” and then we display then we display the place to Stay in Slovenia. 
12.	Headers
•	On desktop, the images for each headers are cropped weirdly.
o	Home => image ok
o	Search => we just see a bit of the back of a person
o	Add a recommendation => this is so cropped that we can’t identify what this is 
o	FAQ => we see someone’s hair
o	About us => the positioning is OK but I don’t like this picture. Can we swap for the lady facing the lake, or the girl with her dog?

13.	FAQ
•	Font not consistent: FAQ in white bottom left of the header should be bigger (same size as on the “About us” header”).

14.	About us
•	What is SitSpot?
Can we add some space in between paragraphs? Currently a bit difficult to read
•	Why do we exist
The copy isn’t the most up to date. Please take this one https://1drv.ms/w/s!AjYAThCZglCyxhm3fI_06BYvUGkW?e=wlmMwT 
•	Our Values
We are missing a space between each sentence
•	Meet the founder
The copy isn’t the most up to date. Please take this one https://1drv.ms/w/s!AjYAThCZglCyxhm3fI_06BYvUGkW?e=wlmMwT

**Comment by teenie-quaggard** [comment]
Hi @aminalakhsham and team!

I have just got off the phone with Katia and we have both agreed that there are a few things that we would like to see prioritized. I know that both of us have already mentioned a number of small bugs / styling issues, but if **for Monday we could focus please on the following:**

1. The add a recommendation flow needs to be complete. At the moment both Katia and I cannot get passed adding a photo.
In addition:
- The fields for name, place, city and type of Sitspot should be mandatory inputs
- Users should be able to select more than 'place to stay' for type of Sitspot

2. We would please like to see an individual Sitspot rendered from the database so that we can test the search functionality

3. Search functionality should be demonstrable.

We are planning for an in person meeting on Monday afternoon (hopefully 1-3pm London time) so please let me know if you think that this is achievable before then. We can then focus on the smaller flow and styling issues for the rest of the week.

Thank you again for all of your work! We are in the final week! 🎉

**Comment by KatiaSitspot** [comment]
Hi, this is NOT a priority, but before I forget, I wanted to say that it would be good to give users a bit of an explanation once they have clicked on "Add a recommendation". So somewhere above or under the 7 steps, we could have copy saying:

Thank you for sharing your “sitspot”. You’re on your way to support a deserving tourism business and enlighten other conscious travellers like you. Our simple questionnaire will take 15 minutes at most to complete, and will prompt you to share the details that your fellow conscious travellers will find most helpful.

**Comment by teenie-quaggard** [comment]
Additional notes from speaking to Katia:

1. On add a recommendation:
- name should be a required field
- country should be a required field 
-

**Comment by Amoodaa** [comment]
https://sitspot.herokuapp.com/sitspot/stay/22 Here is the finished single place page, you can check it soon
the search functionality hasn't changed but it just doesn't search when the search page loads so bear for today and click the search button twice.

**Comment by Amoodaa** [comment]
An important question, Did you edit the final sitspot stay Typeform? because I saw some new changes that were not there, and potentially it could break the integration between Airtable and Typeform, so please refrain from editing anything without notice.
PS: because when we connected Airtable and Typeform, the fields in the Airtable had to be exactly identical, and the type, and options in the multi/single select question, had to be EXACTLY the same, or else it wouldn't let us connect them

**Comment by KatiaSitspot** [comment]
Yes i did do some minor changes. I’m very sorry i understood that i could edit the copy on the Typeform as i wanted with no impact. We can discuss tomorrow the changes that i have made if that helps?I ve very sorry for the inconvenience caused ...Katia
Katia HERAULTM: 07825189550




On Sun, Nov 17, 2019 at 7:37 PM +0000, "Imad Shatali" <notifications@github.com> wrote:












An important question, Did you edit the final sitspot stay Typeform? because I saw some new changes that were not there, and potentially it could break the integration between Airtable and Typeform, so please refrain from editing anything without notice.

PS: because when we connected Airtable and Typeform, the fields in the Airtable had to be exactly identical, and the type, and options in the multi/single select question, had to be EXACTLY the same, or else it wouldn't let us connect them

**Comment by Amoodaa** [comment]
It's fine, I fixed the stay, and did the same minor changes on the eat, like the `n/a > N/A` and connected the eat, ill try to finish the shop too.
Don't sweat it. nothing serious!
