### ISSUE TITLE
Call tomorrow

### ISSUE THREAD

**Issue by teenie-quaggard** [GSG-G7/sitspot#91]
Hi @KatiaSitspot!
Sorry for the late notice but I’ve had a meeting be rescheduled for 2pm. As it is with a number of individuals it makes it really hard to find a time that works for all. Would you be able instead to have a call at 10:45 instead of 2? Sorry about a shuffle, I hope we can make it work!
Thanks Katia.

**Comment by KatiaSitspot** [comment]
10.45 works for meKatia
Katia HERAULTM: 07825189550

**Comment by teenie-quaggard** [comment]
@KatiaSitspot - thank you, that’s great. Speak then!
